// map path and base url to jest config: https://kulshekhar.github.io/ts-jest/user/config/
var { pathsToModuleNameMapper } = require("ts-jest/utils");
const { compilerOptions } = require("./tsconfig");

module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  // map path and base url to jest config
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
    prefix: "<rootDir>/"
  }),
  testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.[t]sx?$",
  watchPathIgnorePatterns: [
    // index file. generated by codegen test file
    "index.ts"
  ]
};
