var { pathsToModuleNameMapper } = require("ts-jest/utils");

module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  testPathIgnorePatterns: ["__test__.+/test.ts"],
  watchPathIgnorePatterns: [
    // index file. generated by codegen test file
    "index.ts",
    "index.js"
  ]
};
