var { pathsToModuleNameMapper } = require("ts-jest/utils");
const { compilerOptions } = require("./tsconfig.json");

module.exports = {
  preset: "ts-jest",
  // moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
  //   prefix: "<rootDir>/"
  // }),
  testEnvironment: "node",
  testPathIgnorePatterns: [
    "__test__.+/test.ts",
    "__test__.+/a.ts",
    "__test__.+/index.ts",
    "__test__.+/index2.ts"
  ],
  watchPathIgnorePatterns: [
    // index file. generated by codegen test file
    "index.ts",
    "index.js"
  ]
};
